export const LAWS = {
  hive: {
    l000: {
      id: "l000",
      cost: [1],
      max: 1,
      img: "l000.webp",
      incomeType: "once",
      income: {
        gold: 2500,
        wood: 5,
        ore: 5,
      },
      limit: 0,
      title: "Resource Riches I",
      description: () =>
        "Provides a one-time allotment of 2500 Gold, 5 Wood, and 5 Ore when enacted.",
    },
    l010: {
      id: "l010",
      cost: [1, 1],
      max: 2,
      img: "l010.webp",
      incomeType: "none",
      limit: 0,
      bonus: {
        limit: ({ lvl }: LVL) => Math.min(4, lvl * 2),
      },
      title: "Laws of the Hive",
      description: ({ lvl }: LVL) =>
        `Requirements for unlocking higher-level Laws are reduced by ${Math.min(4, lvl * 2)}.`,
    },
    l020: {
      id: "l020",
      cost: [2, 2, 2],
      max: 3,
      img: "l020.webp",
      incomeType: "none",
      limit: 0,
      title: "Mana Devour",
      description: ({ lvl }: LVL) =>
        `Your heroes' spells const  -${Math.min(3, lvl)} mana`,
    },
    l030: {
      id: "l030",
      cost: [4],
      max: 1,
      img: "l030.webp",
      incomeType: "none",
      limit: 0,
      title: "Focus Reserves",
      description: () => "Start each battle with +1 Focus Charge(s).",
    },
    l100: {
      id: "l100",
      cost: [2, 2, 2],
      max: 3,
      img: "l100.webp",
      incomeType: "daily",
      income: {
        gold: 250,
      },
      limit: 5,
      title: "Tax Collectors",
      description: ({ lvl }: LVL) =>
        `Produces ${Math.min(750, lvl * 250)} Gold daily.`,
    },
    l110: {
      id: "l110",
      cost: [2, 2],
      max: 2,
      img: "l110.webp",
      incomeType: "daily",
      income: {
        crystals: 1,
      },
      limit: 5,
      title: "Mining: Crystals",
      description: ({ lvl }: LVL) =>
        `Produces ${Math.min(2, lvl)} Crystal(s) daily.`,
    },
    l120: {
      id: "l120",
      cost: [3],
      max: 1,
      img: "l120.webp",
      incomeType: "none",
      limit: 5,
      title: "Hidden Desires",
      description: ({ sight }: Sight) =>
        `Your Hive heroes see exact information about neutral squads within ${3 * sight} squares.`,
    },
    l200: {
      id: "l200",
      cost: [2],
      max: 1,
      img: "l200.webp",
      incomeType: "once",
      income: {
        gold: 5000,
        wood: 10,
        ore: 10,
      },
      limit: 15,
      title: "Resource Riches II",
      description: () =>
        "Provides a one-time allotment of 5000 Gold, 10 Wood, and 10 Ore when enacted.",
    },
    l210: {
      id: "l210",
      cost: [4],
      max: 1,
      img: "l210.webp",
      incomeType: "none",
      limit: 15,
      title: "Natural Selection",
      description: () =>
        "External dwellings in an area that you control produce upgraded creatures.",
    },
    l220: {
      id: "l220",
      cost: [3],
      max: 1,
      img: "l220.webp",
      incomeType: "none",
      limit: 15,
      title: "Ancient Power",
      description: () => "Primal spells of your heroes gain 1 level(s).",
    },
    l300: {
      id: "l300",
      cost: [4, 4],
      max: 2,
      img: "l300.webp",
      incomeType: "none",
      limit: 30,
      title: "Prosper and Flourish",
      description: ({ lvl }: LVL) =>
        `External dwellings increase respective creature growth in the cities by ${Math.min(100, lvl * 50)}.`,
    },
    l310: {
      id: "l310",
      cost: [3],
      max: 1,
      img: "l310.webp",
      incomeType: "none",
      limit: 30,
      title: "Beelzebub's Gaze",
      description: ({ sight }: Sight) =>
        `Your Hive heroes see exact information about enemy heroes and cities within ${3 * sight} squares.`,
    },
    l400: {
      id: "l400",
      cost: [4, 4],
      max: 2,
      img: "l400.webp",
      incomeType: "none",
      limit: 50,
      title: "Evolve, Adapt, Overcome",
      description: ({ lvl }: LVL) =>
        `Upgrading your Hive creatures costs –${Math.min(20, lvl * 10)}% Gold. Recruiting upgraded creatures is discounted by the same amount.`,
    },
    l410: {
      id: "l410",
      cost: [3],
      max: 1,
      img: "l410.webp",
      incomeType: "once",
      income: {
        gold: 7500,
        wood: 15,
        ore: 15,
      },
      limit: 50,
      title: "Resource Riches III",
      description: () =>
        "Provides a one-time allotment of 7500 Gold, 15 Wood, and 15 Ore when enacted.",
    },
    l420: {
      id: "l420",
      cost: [3, 3, 3],
      max: 3,
      img: "l420.webp",
      incomeType: "none",
      limit: 50,
      title: "Hive Magic",
      description: ({ lvl }: LVL) =>
        `Your heroes deal +${Math.min(30, lvl * 10)}% Magic Damage.`,
    },
    l001: {
      id: "l001",
      cost: [2, 2, 2],
      max: 3,
      img: "l001.webp",
      incomeType: "none",
      limit: 0,
      title: "Hive Integration",
      description: ({ lvl }: LVL) =>
        `Friendly creatures gain ${Math.min(3, lvl)} Attack.`,
    },
    l011: {
      id: "l011",
      cost: [2, 2, 2],
      max: 3,
      img: "l011.webp",
      incomeType: "none",
      limit: 0,
      title: "Hive Reception",
      description: ({ lvl }: LVL) =>
        `Friendly creatures gain ${Math.min(3, lvl)} Defense.`,
    },
    l021: {
      id: "l021",
      cost: [3],
      max: 1,
      img: "l021.webp",
      incomeType: "none",
      limit: 0,
      title: "Hive Offsprings I",
      description: () => `Summoned Fire Larvae deal +50% Damage on death.`,
    },
    l101: {
      id: "l101",
      cost: [3, 2],
      max: 2,
      img: "l101.webp",
      incomeType: "none",
      limit: 5,
      title: "Elite Parasites",
      description: ({ lvl }: LVL) =>
        `Parasite growth in your cities increases by 4. They gain ${Math.min(2, lvl)} HP.`,
    },
    l111: {
      id: "l111",
      cost: [3, 2],
      max: 2,
      img: "l111.webp",
      incomeType: "none",
      limit: 5,
      title: "Elite Locusts",
      description: ({ lvl }: LVL) =>
        `Locust growth in your cities increases by 4. They gain ${Math.min(2, lvl)} Speed.`,
    },
    l121: {
      id: "l121",
      cost: [3, 2],
      max: 2,
      img: "l121.webp",
      incomeType: "none",
      limit: 5,
      title: "Elite Hornets",
      description: ({ lvl }: LVL) =>
        `Hornet growth in your cities increases by 2. They gain ${Math.min(2, lvl)} Initiative.`,
    },
    l201: {
      id: "l201",
      cost: [3, 2],
      max: 2,
      img: "l201.webp",
      incomeType: "none",
      limit: 15,
      title: "Elite Scorpions",
      description: ({ lvl }: LVL) =>
        `Hornet growth in your cities increases by 2. They gain ${lvl >= 2 ? 3 : 1} Initiative.`,
    },
    l211: {
      id: "l211",
      cost: [3, 2],
      max: 2,
      img: "l211.webp",
      incomeType: "none",
      limit: 15,
      title: "Elite Reavers",
      description: ({ lvl }: LVL) =>
        `Reaver growth in your cities increases by 1. They gain ${lvl >= 2 ? 5 : 1} Morale and 1 Luck.`,
    },
    l221: {
      id: "l221",
      cost: [3, 2],
      max: 2,
      img: "l221.webp",
      incomeType: "none",
      limit: 15,
      title: "Elite Waurmos",
      description: ({ lvl }: LVL) =>
        `Waurms growth in your cities increases by 1. They gain ${lvl >= 2 ? 5 : 1} Morale and 1 Luck.`,
    },
    l231: {
      id: "l231",
      cost: [4],
      max: 1,
      img: "l231.webp",
      incomeType: "none",
      limit: 15,
      title: "Hive Offsprings II",
      description: () => `Summoned Fire Larvae provoke adjacent enemies to attack them over other units.`,
    },
    l301: {
      id: "l301",
      cost: [3, 2],
      max: 2,
      img: "l301.webp",
      incomeType: "none",
      limit: 30,
      title: "Elite Hive Queens",
      description: ({ lvl }: LVL) =>
        `Hive Queen growth in your cities increases by 1. They deal +${Math.min(10, lvl * 5)} Damage and gain ${Math.min(50, lvl * 25)} HP.`,
    },
    l311: {
      id: "l311",
      cost: [2, 2, 2],
      max: 3,
      img: "l311.webp",
      incomeType: "none",
      limit: 30,
      title: "Elite Hive Queens",
      description: ({ lvl }: LVL) =>
        `When battling in the area you do not control, friendly creatures gain ${Math.min(6, lvl * 2)} Attack and Defense.`,
    },
    l401: {
      id: "l401",
      cost: [4, 4],
      max: 2,
      img: "l401.webp",
      incomeType: "none",
      limit: 50,
      title: "Infernal Rage",
      description: ({ lvl }: LVL) =>
        `Friendly creatures deal +${Math.min(2, lvl)} Damage.`,
    },
    l411: {
      id: "l411",
      cost: [3, 3, 3],
      max: 3,
      img: "l411.webp",
      incomeType: "none",
      limit: 50,
      title: "No Compassion",
      description: ({ lvl }: LVL) =>
        `The chance of Morale or Luck triggering for friendly creatures increases by ${Math.min(3, lvl)}% for each point of their Morale or Luck, respectively.`,
    },
    l421: {
      id: "l421",
      cost: [5],
      max: 1,
      img: "l421.webp",
      incomeType: "none",
      limit: 50,
      title: "Hive Offsprings III",
      description: () =>
        `Summoned Fire Larvae attack twice.`,
    },
  },
  schism: {
    l000: {
      id: "l000",
      cost: [1],
      max: 1,
      img: "l000.webp",
      incomeType: "once",
      income: {
        gold: 2500,
        wood: 5,
        ore: 5,
      },
      limit: 0,
      title: "Resource Riches I",
      description: () =>
        "Provides a one-time allotment of 2500 Gold, 5 Wood, and 5 Ore when enacted.",
    },
    l010: {
      id: "l010",
      cost: [2, 2, 2],
      max: 3,
      img: "l010.webp",
      incomeType: "once",
      limit: 0,
      title: "Inevitable Destruction",
      description: ({ lvl }: LVL) =>
        `When destroying artifacts, you gain +${Math.min(30, lvl * 10)}% Alchemical Dust.`,
    },
    l020: {
      id: "l020",
      cost: [2, 2, 2],
      max: 3,
      img: "l020.webp",
      incomeType: "once",
      limit: 0,
      title: "Depths of Mind",
      description: ({ lvl }: LVL) =>
        `Your Schism heroes restore +${Math.min(15, lvl * 5)}% mana each morning.`,
    },
    l001: {
      id: "l001",
      cost: [3, 2],
      max: 2,
      img: "l001.webp",
      incomeType: "once",
      limit: 0,
      title: "Elite Ra'Shoth",
      description: ({ lvl }: LVL) =>
        `Ra’Shoth growth in your cities increases by ${Math.min(8, lvl * 4)}. They gain 1 Initiative.`,
    },
    l011: {
      id: "l011",
      img: "l011.webp",
      cost: [2],
      max: 1,
      incomeType: "once",
      limit: 0,
      title: "Unfrozen Strength I",
      description: () =>
        `Tier-1 friendly creatures gain 10% of their hero’s Attack and Spell Power as Attack, 10% of their Defense and Knowledge as Defense.`,
    },
    l021: {
      id: "l021",
      img: "l021.webp",
      cost: [3, 3, 3],
      max: 3,
      incomeType: "once",
      limit: 0,
      title: "Frozen Homeland",
      description: ({ lvl }: LVL) =>
        `Friendly creatures gain ${Math.min(3, lvl)} Attack and Defense when they battle on their Native Terrain.`,
    },
    l100: {
      id: "l100",
      img: "l100.webp",
      cost: [2, 2],
      max: 2,
      incomeType: "daily",
      income: {
        gold: 250,
      },
      limit: 5,
      title: "Tax Collectors",
      description: ({ lvl }: LVL) =>
        `Produces ${Math.min(750, lvl * 250)} Gold daily.`,
    },
    l110: {
      id: "l110",
      cost: [2, 2],
      max: 2,
      img: "l110.webp",
      incomeType: "daily",
      income: {
        mercury: 1,
      },
      limit: 5,
      title: "Mining: Mercury",
      description: ({ lvl }: LVL) =>
        `Produces ${Math.min(2, lvl)} Mercury daily.`,
    },
    l120: {
      id: "l120",
      cost: [4, 4],
      max: 2,
      img: "l120.webp",
      incomeType: "none",
      limit: 5,
      title: "Generational Wisdom",
      description: ({ lvl }: LVL) =>
        `Your heroes gain +${Math.min(20, lvl * 10)}% XP.`,
    },
    l130: {
      id: "l130",
      cost: [2, 2, 2],
      max: 3,
      img: "l130.webp",
      incomeType: "none",
      limit: 5,
      title: "Ice Power",
      description: ({ lvl }: LVL) =>
        `Your heroes gain +${Math.min(3, lvl)} Spell Power.`,
    },
    l101: {
      id: "l101",
      img: "l101.webp",
      cost: [3],
      max: 1,
      incomeType: "none",
      limit: 5,
      title: "Elite Cultists",
      description: () =>
        `Cultist growth in your cities increases by 4. They deal +1 Damage.`,
    },
    l111: {
      id: "l111",
      img: "l111.webp",
      cost: [3],
      max: 1,
      incomeType: "none",
      limit: 5,
      title: "Elite Aga'Shoth Riders",
      description: () =>
        `Aga’Shoth Rider growth in your cities increases by 2. They gain 5 HP.`,
    },
    l121: {
      id: "l121",
      img: "l121.webp",
      cost: [2],
      max: 1,
      incomeType: "none",
      limit: 5,
      title: "Unfrozen Strength II",
      description: () =>
        `Tier-2 friendly creatures gain 10% of their hero’s Attack and Spell Power as Attack,10% of their Defense and Knowledge as Defense.`,
    },
    l131: {
      id: "l131",
      img: "l131.webp",
      cost: [2],
      max: 1,
      incomeType: "none",
      limit: 5,
      title: "Unfrozen Strength III",
      description: () =>
        `Tier-3 friendly creatures gain 10% of their hero’s Attack and Spell Power as Attack, 10% of their Defense and Knowledge as Defense.`,
    },
    l200: {
      id: "l200",
      img: "l200.webp",
      cost: [2],
      max: 1,
      incomeType: "once",
      income: {
        gold: 5000,
        wood: 10,
        ore: 10,
      },
      limit: 15,
      title: "Resource Riches II",
      description: () =>
        `Provides a one-time allotment of 5000 Gold, 10 Wood, and 10 Ore when enacted.`,
    },
    l220: {
      id: "l220",
      img: "l220.webp",
      cost: [3],
      max: 1,
      incomeType: "none",
      limit: 15,
      title: "Otherworldly Magic",
      description: () => `Arcane spells of your heroes gain 1 level.`,
    },
    l230: {
      id: "l230",
      img: "l230.webp",
      cost: [2, 2, 2],
      max: 3,
      incomeType: "none",
      limit: 15,
      title: "Call of the Deep",
      description: ({ lvl }: LVL) =>
        `Your Schism heroes’ spells and friendly creatures’ abilities summon +${Math.min(30, lvl * 10)}% units.`,
    },
    l201: {
      id: "l201",
      img: "l201.webp",
      cost: [3, 2],
      max: 2,
      incomeType: "none",
      limit: 15,
      title: "Elite Grand Shoth",
      description: ({ lvl }: LVL) =>
        `Grand Shoth growth in your cities increases by ${Math.min(4, lvl * 2)}. They gain 1 Speed.`,
    },
    l211: {
      id: "l211",
      img: "l211.webp",
      cost: [2],
      max: 1,
      incomeType: "none",
      limit: 15,
      title: "Unfrozen Strength IV",
      description: () =>
        `Tier-4 friendly creatures gain 10% of their hero’s Attack and Spell Power as Attack, 10% of their Defense and Knowledge as Defense.`,
    },
    l221: {
      id: "l221",
      img: "l221.webp",
      cost: [4, 4],
      max: 2,
      incomeType: "none",
      limit: 15,
      title: "Cold Touch",
      description: ({ lvl }: LVL) =>
        `All effects applied by your heroes and friendly creatures last ${Math.min(2, lvl)} additional round(s).`,
    },
    l210: {
      id: "l210",
      img: "l210.webp",
      cost: [3, 3],
      max: 2,
      incomeType: "daily",
      income: {
        wood: 1,
        ore: 1,
      },
      limit: 30,
      title: "Survival Conditions",
      description: ({ lvl }: LVL) =>
        `Your cities produce +${Math.min(2, lvl)} Wood and Ore.`,
    },
    l300: {
      id: "l300",
      img: "l300.webp",
      cost: [3, 3, 3],
      max: 3,
      incomeType: "none",
      limit: 30,
      title: "Planar Explorers",
      description: ({ lvl }: LVL) =>
        `Produces ${Math.min(1500, lvl * 500)} Astrology points daily.`,
    },
    l310: {
      id: "l310",
      img: "l310.webp",
      cost: [3],
      max: 1,
      incomeType: "none",
      limit: 30,
      title: "Absolute Zero",
      description: () =>
        `The cooldowns of all the battle spells of enemy heroes are increased by 1 round(s).`,
    },
    l320: {
      id: "l320",
      img: "l320.webp",
      cost: [6],
      max: 1,
      incomeType: "none",
      limit: 30,
      title: "Cold Shoulder",
      description: () =>
        `You can use Involuntary Summons in your Schism cities twice per week.`,
    },
    l301: {
      id: "l301",
      img: "l301.webp",
      cost: [3],
      max: 1,
      incomeType: "none",
      limit: 30,
      title: "Elite Concubi",
      description: () =>
        `Concubus growth in your cities increases by 1. They gain 4 Attack and Defense.`,
    },
    l311: {
      id: "l311",
      img: "l311.webp",
      cost: [3],
      max: 1,
      incomeType: "none",
      limit: 30,
      title: "Elite Arbitrators",
      description: () =>
        `Arbitrator growth in your cities increases by 1. They deal +4 Damage.`,
    },
    l321: {
      id: "l321",
      img: "l321.webp",
      cost: [2],
      max: 1,
      incomeType: "none",
      limit: 30,
      title: "Unfrozen Strength V",
      description: () =>
        `Tier-5 friendly creatures gain 10% of their hero’s Attack and Spell Power as Attack, 10% of their Defense and Knowledge as Defense.`,
    },
    l331: {
      id: "l331",
      img: "l331.webp",
      cost: [2],
      max: 1,
      incomeType: "none",
      limit: 30,
      title: "Unfrozen Strength VI",
      description: () =>
        `Tier-6 friendly creatures gain 10% of their hero’s Attack and Spell Power as Attack, 10% of their Defense and Knowledge as Defense.`,
    },
    l400: {
      id: "l400",
      img: "l400.webp",
      cost: [3],
      max: 1,
      incomeType: "once",
      income: {
        gold: 7500,
        wood: 15,
        ore: 15,
      },
      limit: 50,
      title: "Resource Riches III",
      description: () =>
        `Provides a one-time allotment of 7500 Gold, 15 Wood, and 15 Ore when enacted.`,
    },
    l410: {
      id: "l410",
      img: "l410.webp",
      cost: [4],
      max: 1,
      incomeType: "none",
      limit: 50,
      title: "Mind Freeze",
      description: () =>
        `Each round of battle, the enemy loses 1 Focus Charge(s).`,
    },
    l330: {
      id: "l330",
      img: "l330.webp",
      cost: [4],
      max: 1,
      incomeType: "none",
      limit: 50,
      title: "The Abyss Stares Back",
      description: () =>
        `Your Schism heroes start each day with maximum Communion level.`,
    },
    l430: {
      id: "l430",
      img: "l430.webp",
      cost: [6],
      max: 1,
      incomeType: "none",
      limit: 50,
      title: "The World is Ours",
      description: () => `Friendly creatures treat all Terrains as Native.`,
    },
    l401: {
      id: "l401",
      img: "l401.webp",
      cost: [3, 2],
      max: 2,
      incomeType: "none",
      limit: 50,
      title: "Elite Abyssal Envoys",
      description: ({ lvl }: LVL) =>
        `Abyssal Envoy growth in your cities increases by ${Math.min(2, lvl)}. They gain 2 Speed and Initiative.`,
    },
    l411: {
      id: "l411",
      img: "l411.webp",
      cost: [2],
      max: 1,
      incomeType: "none",
      limit: 50,
      title: "Unfrozen strength VII",
      description: () =>
        `Tier-7 friendly creatures gain 10% of their hero’s Attack and Spell Power as Attack, 10% of their Defense and Knowledge as Defense.`,
    },
    l421: {
      id: "l421",
      img: "l421.webp",
      cost: [5],
      max: 1,
      incomeType: "none",
      limit: 50,
      title: "Ice Storms",
      description: () => `All enemy creatures lose 1 Speed and Initiative.`,
    },
  },
  dungeon: {
    l000: {
      id: "l000",
      cost: [1],
      max: 1,
      img: "l000.webp",
      incomeType: "once",
      income: {
        gold: 2500,
        wood: 5,
        ore: 5,
      },
      limit: 0,
      title: "Resource Riches I",
      description: () =>
        "Provides a one-time allotment of 2500 Gold, 5 Wood, and 5 Ore when enacted.",
    },
    l010: {
      id: "l010",
      cost: [6],
      max: 1,
      img: "l010.webp",
      incomeType: "daily",
      limit: 0,
      income: {
        astrology: 500,
      },
      title: "Arcane Knowledge",
      description: () => `Produces 500 Astrology points daily.`,
    },
    l020: {
      id: "l020",
      cost: [3, 3],
      max: 2,
      img: "l020.webp",
      incomeType: "none",
      limit: 0,
      bonus: {
        law: 10,
      },
      title: "Leaders of the Nation",
      description: ({ lvl }: LVL) =>
        `Your heroes generate ${Math.min(20, lvl * 10)}% Law points.`,
    },
    l001: {
      id: "l001",
      cost: [3, 2],
      max: 2,
      img: "l001.webp",
      incomeType: "none",
      limit: 0,
      title: "Elite Troglodytes",
      description: ({ lvl }: LVL) =>
        `Your Troglodytes deal 1.5 times more Damage when using their Fighting Style. Their min. Damage increases by ${Math.min(2, lvl)}.`,
    },
    l011: {
      id: "l011",
      cost: [2],
      max: 1,
      img: "l011.webp",
      incomeType: "none",
      limit: 0,
      title: "Dungeon Masters I",
      description: () =>
        `Tier-1 creature growth in your cities increases by 4.`,
    },
    l021: {
      id: "l021",
      cost: [2, 2, 2],
      max: 3,
      img: "l021.webp",
      incomeType: "none",
      limit: 0,
      title: "Dragon Scales",
      description: ({ lvl }: LVL) =>
        `Friendly creatures take –${Math.min(15, lvl * 5)}% Magic Damage.`,
    },
    l100: {
      id: "l100",
      cost: [2, 2],
      max: 2,
      img: "l100.webp",
      incomeType: "daily",
      income: {
        gold: 250,
      },
      limit: 5,
      title: "Tax Collectors",
      description: ({ lvl }: LVL) =>
        `Produces ${Math.min(500, lvl * 250)} Gold daily.`,
    },
    l110: {
      id: "l110",
      cost: [2, 2],
      max: 2,
      img: "l110.webp",
      incomeType: "daily",
      income: {
        gems: 1,
      },
      limit: 5,
      title: "Mining: Gems",
      description: ({ lvl }: LVL) =>
        `Produces ${Math.min(2, lvl)} Gem(s) daily.`,
    },
    l120: {
      id: "l120",
      cost: [4],
      max: 1,
      img: "l120.webp",
      incomeType: "once",
      income: {
        dust: 75,
      },
      limit: 5,
      title: "Alchemists Code I",
      description: () =>
        `Provides a one-time allotment of 75 Alchemical Dust when enacted.`,
    },
    l101: {
      id: "l101",
      cost: [3, 2],
      max: 2,
      img: "l101.webp",
      incomeType: "none",
      limit: 5,
      title: "Elite Infiltrators",
      description: ({ lvl }: LVL) =>
        `Your Infiltrators deal 1.5 times more Damage when using their Fighting Style. They gain ${Math.min(4, lvl * 2)} HP.`,
    },
    l111: {
      id: "l111",
      cost: [3, 2],
      max: 2,
      img: "l111.webp",
      incomeType: "none",
      limit: 5,
      title: "Elite Dancers",
      description: ({ lvl }: LVL) =>
        `Your Onyx Dancers deal 1.5 times more Damage when using their Fighting Style. They gain ${Math.min(4, lvl * 2)} Attack and Defense.`,
    },
    l121: {
      id: "l121",
      cost: [3],
      max: 1,
      img: "l121.webp",
      incomeType: "none",
      limit: 5,
      title: "Dungeon Masters II",
      description: () =>
        `Tier-2 creature growth in your cities increases by 4.`,
    },
    l131: {
      id: "l131",
      img: "l131.webp",
      cost: [3],
      max: 1,
      incomeType: "none",
      limit: 5,
      title: "Dungeon Masters III",
      description: () =>
        `Tier-3 creature growth in your cities increases by 2.`,
    },
    l200: {
      id: "l200",
      img: "l200.webp",
      cost: [2],
      max: 1,
      incomeType: "once",
      income: {
        gold: 5000,
        wood: 10,
        ore: 10,
      },
      limit: 15,
      title: "Resource Riches II",
      description: () =>
        `Provides a one-time allotment of 5000 Gold, 10 Wood, and 10 Ore when enacted.`,
    },
    l210: {
      id: "l210",
      img: "l210.webp",
      cost: [3, 3],
      max: 2,
      incomeType: "none",
      limit: 15,
      title: "Or No Ore?",
      description: ({ lvl }: LVL) =>
        `Your buildings cost –${Math.min(40, lvl * 20)}% Ore to construct.`,
    },
    l220: {
      id: "l220",
      img: "l220.webp",
      cost: [5, 5],
      max: 2,
      incomeType: "none",
      limit: 15,
      title: "Jadame Maps",
      description: ({ lvl }: LVL) =>
        `Your heroes gain ${Math.min(20, lvl * 10)} Movement points.`,
    },
    l230: {
      id: "l230",
      img: "l230.webp",
      cost: [2, 2, 2],
      max: 3,
      incomeType: "none",
      limit: 15,
      title: "Spy Network",
      description: ({ lvl }: LVL) =>
        `All external buildings and structures under your control gain +${Math.min(6, lvl * 2)} sight radius.`,
    },
    l201: {
      id: "l201",
      img: "l201.webp",
      cost: [3, 2],
      max: 2,
      incomeType: "none",
      limit: 15,
      title: "Elite Minotaurs",
      description: ({ lvl }: LVL) =>
        `Your Minotaurs deal 1.5 times more Damage when using their Fighting Style. They gain 1 Speed and Initiative and deal +${Math.min(4, lvl * 2)} Damage.`,
    },
    l211: {
      id: "l211",
      img: "l211.webp",
      cost: [3, 2],
      max: 2,
      incomeType: "none",
      limit: 15,
      title: "Elite Medusae",
      description: ({ lvl }: LVL) =>
        `Your Medusae deal 1.5 times more Damage when using their Fighting Style. They gain ${Math.min(2, lvl)} Initiative and 4 Attack and Defense.`,
    },
    l221: {
      id: "l221",
      img: "l221.webp",
      cost: [6],
      max: 1,
      incomeType: "none",
      limit: 15,
      title: "Tactical Advantage",
      description: () => `All enemy creatures lose 1 Initiative.`,
    },
    l231: {
      id: "l231",
      img: "l231.webp",
      cost: [3],
      max: 1,
      incomeType: "none",
      limit: 15,
      title: "Dungeon Masters IV",
      description: () =>
        `Tier-4 creature growth in your cities increases by 2.`,
    },
    l300: {
      id: "l300",
      img: "l300.webp",
      cost: [6],
      max: 1,
      incomeType: "none",
      limit: 30,
      title: "Merchants Guild",
      description: () => `Eliminates all price markups in the Marketplace.`,
    },
    l310: {
      id: "l310",
      img: "l310.webp",
      cost: [5, 5],
      max: 2,
      incomeType: "none",
      limit: 30,
      title: "Triumvirate's Agents",
      description: ({ lvl }: LVL) =>
        `Your Dungeon heroes gain ${Math.min(2, lvl)} to all attributes.`,
    },
    l320: {
      id: "l320",
      img: "l320.webp",
      cost: [4],
      max: 1,
      incomeType: "once",
      income: {
        dust: 150,
      },
      limit: 30,
      title: "Alchemists Code II",
      description: () =>
        `Provides a one-time allotment of 150 Alchemical Dust when enacted.`,
    },
    l330: {
      id: "l330",
      img: "l330.webp",
      cost: [3, 3],
      max: 2,
      incomeType: "none",
      limit: 30,
      title: "Peoples of Jadame",
      description: ({ lvl }: LVL) =>
        `Your heroes’ Persuasion Power in Diplomacy increases by ${Math.min(20, lvl * 10)}%.`,
    },
    l301: {
      id: "l301",
      img: "l301.webp",
      cost: [3, 2],
      max: 2,
      incomeType: "none",
      limit: 30,
      title: "Elite Hydras",
      description: ({ lvl }: LVL) =>
        `Your Hydras deal 1.5 times more Damage when using their Fighting Style. They gain ${Math.min(2, lvl)} Speed and 25 HP.`,
    },
    l311: {
      id: "l311",
      img: "l311.webp",
      cost: [3],
      max: 1,
      incomeType: "none",
      limit: 30,
      title: "Dungeon Masters V",
      description: () =>
        `Tier-5 creature growth in your cities increases by 1.`,
    },
    l321: {
      id: "l321",
      img: "l321.webp",
      cost: [3],
      max: 1,
      incomeType: "none",
      limit: 30,
      title: "Dungeon Masters VI",
      description: () =>
        `Tier-6 creature growth in your cities increases by 1.`,
    },
    l400: {
      id: "l400",
      img: "l400.webp",
      cost: [3],
      max: 1,
      incomeType: "once",
      income: {
        gold: 7500,
        wood: 15,
        ore: 15,
      },
      limit: 50,
      title: "Resource Riches III",
      description: () =>
        `Provides a one-time allotment of 7500 Gold, 15 Wood, and 15 Ore when enacted.`,
    },
    l410: {
      id: "l410",
      img: "l410.webp",
      cost: [4, 4],
      max: 2,
      incomeType: "none",
      limit: 50,
      title: "Magical Education",
      description: ({lvl}: LVL) => `Spells of your heroes gain ${Math.min(2, lvl)} level(s).`,
    },
    l420: {
      id: "l420",
      img: "l420.webp",
      cost: [3],
      max: 1,
      incomeType: "none",
      limit: 50,
      title: "Saturation",
      description: () => `Your Focus Charge limit increases by 1.`,
    },
    l401: {
      id: "l401",
      img: "l401.webp",
      cost: [3, 2],
      max: 2,
      incomeType: "none",
      limit: 50,
      title: "Elite Cave Dragons",
      description: ({ lvl }: LVL) =>
        `Your Cave Dragons deal 1.5 times more Damage, when using their Fighting Style. They gain ${Math.min(8, lvl * 4)} Attack and Defense and ${Math.min(2, lvl)} Speed and Initiative.`,
    },
    l411: {
      id: "l411",
      img: "l411.webp",
      cost: [3],
      max: 1,
      incomeType: "none",
      limit: 50,
      title: "Dungeon Masters VII",
      description: () =>
        `Tier-7 creature growth in your cities increases by 1.`,
    },
  },
  grove: {
    l000: {
      id: "l000",
      img: "l000.webp",
      cost: [1],
      max: 1,
      incomeType: "once",
      income: {
        gold: 2500,
        wood: 5,
        ore: 5,
      },
      limit: 0,
      title: "Resource Riches I",
      description: () =>
        "Provides a one-time allotment of 2500 Gold, 5 Wood, and 5 Ore when enacted.",
    },
    l010: {
      id: "l010",
      img: "l010.webp",
      cost: [3],
      max: 1,
      incomeType: "daily",
      income: {
        gold: 500,
      },
      limit: 0,
      title: "Tax Collectors",
      description: () => "Produces 500 Gold daily.",
    },
    l020: {
      id: "l020",
      img: "l020.webp",
      cost: [2, 2, 2],
      max: 3,
      incomeType: "none",
      limit: 0,
      title: "Knowledge is Power",
      description: ({ lvl }: LVL) =>
        `Your heroes gain ${Math.min(3, lvl)} Knowledge.`,
    },
    l001: {
      id: "l001",
      img: "l001.webp",
      cost: [3, 2, 1],
      max: 3,
      incomeType: "none",
      limit: 0,
      title: "Elite Fauns",
      description: ({ lvl }: LVL) =>
        `Faun growth in your cities increases by ${Math.min(6, lvl * 2)}. They deal +50% Melee Damage.`,
    },
    l011: {
      id: "l011",
      img: "l011.webp",
      cost: [3, 2, 1],
      max: 3,
      incomeType: "none",
      limit: 0,
      title: "Elite Hoplet",
      description: ({ lvl }: LVL) =>
        `Hoplet growth in your cities increases by ${Math.min(6, lvl * 2)}. They always deal maximum Damage.`,
    },
    l100: {
      id: "l100",
      img: "l100.webp",
      cost: [2, 2],
      max: 2,
      incomeType: "daily",
      income: {
        crystals: 1,
      },
      limit: 5,
      title: "Mining: Crystals",
      description: ({ lvl }: LVL) =>
        `Produces ${Math.min(2, lvl)} Crystal(s) daily.`,
    },
    l110: {
      id: "l110",
      img: "l110.webp",
      cost: [1],
      max: 1,
      incomeType: "daily",
      income: {
        astrology: 250,
      },
      limit: 5,
      title: "Clear Sky",
      description: () => `Produces 250 Astrology Points daily.`,
    },
    l120: {
      id: "l120",
      img: "l120.webp",
      cost: [4],
      max: 1,
      incomeType: "none",
      limit: 5,
      title: "Folk Heroes",
      description: () => `Your heroes cost –40% Gold.`,
    },
    l101: {
      id: "l101",
      img: "l101.webp",
      cost: [3, 2, 1],
      max: 3,
      incomeType: "none",
      limit: 5,
      title: "Elite Iriyads",
      description: ({ lvl }: LVL) =>
        `Vine Iriyad growth in your cities increases by 2. They gain ${Math.min(15, lvl * 5)} HP.`,
    },
    l111: {
      id: "l111",
      img: "l111.webp",
      cost: [2, 2],
      max: 2,
      incomeType: "none",
      limit: 5,
      title: "Nature's Wildness",
      description: ({ lvl }: LVL) =>
        `Friendly creatures deal ${Math.min(50, lvl * 25)}% more Damage with Lucky Strikes.`,
    },
    l121: {
      id: "l121",
      img: "l121.webp",
      cost: [2, 2, 2],
      max: 3,
      incomeType: "none",
      limit: 5,
      title: "Veiled by the Treess",
      description: ({ lvl }: LVL) =>
        `When battling in the area you control, friendly creatures gain ${Math.min(6, lvl * 2)} Attack and Defense.`,
    },
    l200: {
      id: "l200",
      img: "l200.webp",
      cost: [2],
      max: 1,
      incomeType: "once",
      income: {
        gold: 5000,
        wood: 10,
        ore: 10,
      },
      limit: 15,
      title: "Resource Riches II",
      description: () =>
        `Provides a one-time allotment of 5000 Gold, 10 Wood, and 10 Ore when enacted.`,
    },
    l210: {
      id: "l210",
      img: "l210.webp",
      cost: [2, 2],
      max: 2,
      incomeType: "none",
      limit: 15,
      title: "Save the Forests",
      description: ({ lvl }: LVL) =>
        `Your buildings cost –${Math.min(40, lvl * 20)}% Wood to construct.`,
    },
    l220: {
      id: "l220",
      img: "l220.webp",
      cost: [4, 4],
      max: 2,
      incomeType: "none",
      limit: 15,
      title: "Forest Magic",
      description: ({ lvl }: LVL) =>
        `Each time you improve a Mage Guild in your Grove cities, +${Math.min(2, lvl)} spell(s) is unlocked in the Observatory.`,
    },
    l230: {
      id: "l230",
      img: "l230.webp",
      cost: [4],
      max: 1,
      incomeType: "none",
      limit: 15,
      title: "Woodland Resistance",
      description: () =>
        `Enemies can’t see detailed information about your armies. (When viewed, it shows random numbers of random Grove units.)`,
    },
    l201: {
      id: "l201",
      img: "l201.webp",
      cost: [3, 2, 1],
      max: 3,
      incomeType: "none",
      limit: 15,
      title: "Elite Naiads",
      description: ({ lvl }: LVL) =>
        `Naiad growth in your cities increases by 2. They gain ${Math.min(3, lvl)} Speed and Initiative.`,
    },
    l211: {
      id: "l211",
      img: "l211.webp",
      cost: [3],
      max: 1,
      incomeType: "none",
      limit: 15,
      title: "Nature's Resolve",
      description: () =>
        `All negative effects on friendly creatures last 1 fewer round(s).`,
    },
    l300: {
      id: "l300",
      img: "l300.webp",
      cost: [4, 4],
      max: 2,
      incomeType: "none",
      limit: 30,
      title: "Fertile Ground",
      description: ({ lvl }: LVL) =>
        `Creature growth of your external dwellings increases by +${Math.min(200, lvl * 100)}%.`,
    },
    l310: {
      id: "l310",
      img: "l310.webp",
      cost: [4, 4, 4],
      max: 3,
      incomeType: "none",
      limit: 30,
      title: "The Power of the Written Word",
      description: ({ lvl }: LVL) =>
        `All temporary spells (scrolls, artifacts etc.) available to your heroes gain ${Math.min(3, lvl)} level(s).`,
    },
    l320: {
      id: "l320",
      img: "l320.webp",
      cost: [4],
      max: 1,
      incomeType: "none",
      limit: 30,
      title: "Natural Serenity",
      description: () =>
        `The cooldowns of all the battle spells of your heroes are reduced by 1 round(s).`,
    },
    l330: {
      id: "l330",
      img: "l330.webp",
      cost: [6],
      max: 1,
      incomeType: "none",
      limit: 30,
      title: "Live roots",
      description: () => `Enemy heroes can’t flee or surrender.`,
    },
    l301: {
      id: "l301",
      img: "l301.webp",
      cost: [3, 2, 1],
      max: 3,
      incomeType: "none",
      limit: 30,
      title: "Elite Mancers",
      description: ({ lvl }: LVL) =>
        `Herbomancer growth in your cities increases by ${Math.min(3, lvl)}. Their abilities cost –1 Focus Charge(s).`,
    },
    l311: {
      id: "l311",
      img: "l311.webp",
      cost: [3, 2, 1],
      max: 3,
      incomeType: "none",
      limit: 30,
      title: "Elite Qilin",
      description: ({ lvl }: LVL) =>
        `Qilin growth in your cities increases by 1. They deal +${Math.min(9, lvl * 3)} Damage.`,
    },
    l321: {
      id: "l321",
      img: "l321.webp",
      cost: [2, 2, 2],
      max: 3,
      incomeType: "none",
      limit: 30,
      title: "Luck of the Fittest",
      description: ({ lvl }: LVL) =>
        `Friendly creatures now have +${Math.min(3, lvl)}% Lucky Strike chance for each point of Luck.`,
    },
    l400: {
      id: "l400",
      img: "l400.webp",
      cost: [3],
      max: 1,
      incomeType: "once",
      income: {
        gold: 7500,
        wood: 15,
        ore: 15,
      },
      limit: 50,
      title: "Resource Riches III",
      description: () =>
        `Provides a one-time allotment of 7500 Gold, 15 Wood, and 15 Ore when enacted.`,
    },
    l410: {
      id: "l410",
      img: "l410.webp",
      cost: [6],
      max: 1,
      incomeType: "none",
      limit: 50,
      title: "Force of Nature",
      description: () => `Your Heroic Strikes deal +20 basic Damage.`,
    },
    l420: {
      id: "l420",
      img: "l420.webp",
      cost: [2, 2],
      max: 2,
      incomeType: "none",
      limit: 50,
      title: "Children of the Wild",
      description: ({ lvl }: LVL) =>
        `Your Grove heroes gain ${Math.min(4, lvl * 2)} sight radius and ${Math.min(20, lvl * 15)} Movement points.`,
    },
    l430: {
      id: "l430",
      img: "l430.webp",
      cost: [3],
      max: 1,
      incomeType: "none",
      limit: 50,
      title: "Focus",
      description: () =>
        `Each round of battle, you generate 1 Focus Charge(s).`,
    },
    l401: {
      id: "l401",
      img: "l401.webp",
      cost: [3, 2, 1],
      max: 3,
      incomeType: "none",
      limit: 50,
      title: "Elite Phoenixes",
      description: ({ lvl }: LVL) =>
        `Phoenix growth in your cities increases by 1. Their maximum Damage increases by ${Math.min(20, lvl * 5 + 5)}.`,
    },
    l411: {
      id: "l411",
      img: "l411.webp",
      cost: [5],
      max: 1,
      incomeType: "none",
      limit: 50,
      title: "Fairy Tale",
      description: () =>
        `Your Fauns, Hoplets and Herbomancers gain 2 Speed and Initiative.`,
    },
    l421: {
      id: "l421",
      img: "l421.webp",
      cost: [5],
      max: 1,
      incomeType: "none",
      limit: 50,
      title: "Sanctuary",
      description: () =>
        `The abilities of your Vine Iriyads, Naiads, Qilins and Phoenixes cost –1 Focus Charge(s).`,
    },
  },
  necropolis: {
    l000: {
      id: "l000",
      img: "l000.webp",
      cost: [1],
      max: 1,
      incomeType: "once",
      income: {
        gold: 2500,
        wood: 5,
        ore: 5,
      },
      limit: 0,
      title: "Resource Riches I",
      description: () =>
        `Provides a one-time allotment of 2500 Gold, 5 Wood, and 5 Ore when enacted.`,
    },
    l010: {
      id: "l010",
      img: "l010.webp",
      cost: [2, 2],
      max: 2,
      incomeType: "daily",
      income: {
        gold: 500,
      },
      limit: 0,
      title: "Tax Collectors",
      description: ({ lvl }: LVL) =>
        `Produces ${Math.min(1000, lvl * 500)} Gold daily.`,
    },
    l020: {
      id: "l020",
      img: "l020.webp",
      cost: [3],
      max: 1,
      incomeType: "none",
      limit: 0,
      title: "Animate Dead I",
      description: () => "Your heroes gain +500 maximum Necromantic Energy.",
    },
    l030: {
      id: "l030",
      img: "l030.webp",
      cost: [2, 2, 2],
      max: 3,
      incomeType: "none",
      limit: 0,
      title: "Gifts of the Afterlife",
      description: ({ lvl }: LVL) =>
        `Your heroes gain ${Math.min(3, lvl)} Luck.`,
    },
    l001: {
      id: "l001",
      img: "l001.webp",
      cost: [3, 2],
      max: 2,
      incomeType: "none",
      limit: 0,
      title: "Elite Skeletons",
      description: ({ lvl }: LVL) =>
        `Skeleton growth in your cities increases by ${Math.min(8, lvl * 4)}. They gain 2 Attack and Defense.`,
    },
    l011: {
      id: "l011",
      img: "l011.webp",
      cost: [3, 2],
      max: 2,
      incomeType: "none",
      limit: 0,
      title: "Elite Wight",
      description: ({ lvl }: LVL) =>
        `Wight growth in your cities increases by ${Math.min(8, lvl * 4)}. Their minimum Damage increases by 1.`,
    },
    l021: {
      id: "l021",
      img: "l021.webp",
      cost: [2, 2],
      max: 2,
      incomeType: "none",
      limit: 0,
      title: "Black Death",
      description: ({ lvl }: LVL) =>
        `Enemy creatures take +${Math.min(50, lvl * 25)}% from Damage-over-time effects.`,
    },
    l100: {
      id: "l100",
      img: "l100.webp",
      cost: [2, 2],
      max: 2,
      incomeType: "daily",
      income: {
        mercury: 1,
      },
      limit: 5,
      title: "Mining: Mercury",
      description: ({ lvl }: LVL) =>
        `Produces ${Math.min(2, lvl)} Mercury daily.`,
    },
    l110: {
      id: "l110",
      img: "l110.webp",
      cost: [2, 2, 2],
      max: 3,
      incomeType: "none",
      limit: 5,
      title: "Stand to the Death!",
      description: ({ lvl }: LVL) =>
        `Your heroes gain ${Math.min(3, lvl)} Defense.`,
    },
    l120: {
      id: "l120",
      img: "l120.webp",
      cost: [3],
      max: 1,
      incomeType: "none",
      limit: 5,
      title: "Animate Dead II",
      description: () => `Your heroes gain +2.5% Necromancy Power.`,
    },
    l130: {
      id: "l130",
      img: "l130.webp",
      cost: [2, 2, 2],
      max: 3,
      incomeType: "none",
      limit: 5,
      title: "Laws of the Immortals",
      description: ({ lvl }: LVL) =>
        `Your cities generate +${Math.min(30, lvl * 10)}% Law points.`,
    },
    l101: {
      id: "l101",
      img: "l101.webp",
      cost: [3, 2],
      max: 2,
      incomeType: "none",
      limit: 5,
      title: "Elite Undead Pets",
      description: ({ lvl }: LVL) =>
        `Undead Pet growth in your cities increases by ${Math.min(4, lvl * 2)}. They gain 2 Initiative.`,
    },
    l111: {
      id: "l111",
      img: "l111.webp",
      cost: [3, 2],
      max: 2,
      incomeType: "none",
      limit: 5,
      title: "Elite Graverobber",
      description: ({ lvl }: LVL) =>
        `Graverobber growth in your cities increases by ${Math.min(4, lvl * 2)}. They summon +50% units.`,
    },
    l121: {
      id: "l121",
      img: "l121.webp",
      cost: [4],
      max: 1,
      incomeType: "none",
      limit: 5,
      title: "Death Equalizes All",
      description: () =>
        `Friendly creatures from different factions don’t decrease each other’s Morale.`,
    },
    l200: {
      id: "l200",
      img: "l200.webp",
      cost: [2],
      max: 1,
      incomeType: "once",
      income: {
        gold: 5000,
        wood: 10,
        ore: 10,
      },
      limit: 15,
      title: "Resource Riches II",
      description: () =>
        `Provides a one-time allotment of 5000 Gold, 10 Wood, and 10 Ore when enacted.`,
    },
    l210: {
      id: "l210",
      img: "l210.webp",
      cost: [3],
      max: 1,
      incomeType: "none",
      limit: 15,
      title: "Moon's Grace",
      description: () => `Nightshade spells of your heroes gain 1 level(s).`,
    },
    l220: {
      id: "l220",
      img: "l220.webp",
      cost: [4],
      max: 1,
      incomeType: "none",
      limit: 15,
      title: "Animate Dead III",
      description: () => `Your heroes gain +500 maximum Necromantic Energy.`,
    },
    l230: {
      id: "l230",
      img: "l230.webp",
      cost: [2, 1, 1],
      max: 3,
      incomeType: "none",
      limit: 15,
      title: "Forbidden Alchemy",
      description: ({ lvl }: LVL) =>
        `Your spell upgrades cost –${Math.min(40, lvl * 10 + 10)}% Alchemical Dust.`,
    },
    l201: {
      id: "l201",
      img: "l201.webp",
      cost: [3, 2],
      max: 2,
      incomeType: "none",
      limit: 15,
      title: "Elite Liches",
      description: ({ lvl }: LVL) =>
        `Lich growth in your cities increases by ${Math.min(2, lvl)}. Their healing abilities restore 50% more HP.`,
    },
    l211: {
      id: "l211",
      img: "l211.webp",
      cost: [3, 2],
      max: 2,
      incomeType: "none",
      limit: 15,
      title: "Elite Dread Knights",
      description: ({ lvl }: LVL) =>
        `Dread Knight growth in your cities increases by ${Math.min(2, lvl)}. Their maximum Damage increases by 6.`,
    },
    l221: {
      id: "l221",
      img: "l221.webp",
      cost: [6],
      max: 1,
      incomeType: "none",
      limit: 15,
      title: "Bloodthirst",
      description: () => `Vampirism of friendly creatures increases by 60%.`,
    },
    l300: {
      id: "l300",
      img: "l300.webp",
      cost: [3, 2, 2],
      max: 3,
      incomeType: "none",
      limit: 30,
      title: "Free Death",
      description: ({ lvl }: LVL) =>
        `Your Necropolis creatures cost –${Math.min(20, lvl * 5 + 5)}% Gold.`,
    },
    l310: {
      id: "l310",
      img: "l310.webp",
      cost: [5],
      max: 1,
      incomeType: "none",
      limit: 30,
      title: "Terra Mortis",
      description: () =>
        `Your Necropolis heroes always battle on their Native Terrain.`,
    },
    l320: {
      id: "l320",
      img: "l320.webp",
      cost: [3],
      max: 1,
      incomeType: "none",
      limit: 30,
      title: "Animate Dead IV",
      description: () => `Your heroes gain +2.5% Necromancy Power.`,
    },
    l301: {
      id: "l301",
      img: "l301.webp",
      cost: [3, 2],
      max: 2,
      incomeType: "none",
      limit: 30,
      title: "Elite Vampires",
      description: ({ lvl }: LVL) =>
        `Vampire growth in your cities increases by ${Math.min(2, lvl)}. They gain 25 HP.`,
    },
    l311: {
      id: "l311",
      img: "l311.webp",
      cost: [4, 4],
      max: 2,
      incomeType: "none",
      limit: 30,
      title: "Return to the Soil",
      description: ({ lvl }: LVL) =>
        `Friendly creatures battling on their Native terrain gain ${Math.min(2, lvl)} Speed.`,
    },
    l321: {
      id: "l321",
      img: "l321.webp",
      cost: [3, 3],
      max: 2,
      incomeType: "none",
      limit: 30,
      title: "Terror and Dread",
      description: ({ lvl }: LVL) =>
        `The chance of Morale or Luck triggering for enemy creatures decreases by ${Math.min(2, lvl)}% for each point of their Morale or Luck, respectively.`,
    },
    l400: {
      id: "l400",
      img: "l400.webp",
      cost: [3],
      max: 1,
      incomeType: "once",
      income: {
        gold: 7500,
        wood: 15,
        ore: 15,
      },
      limit: 50,
      title: "Resource Riches III",
      description: () =>
        `Provides a one-time allotment of 7500 Gold, 15 Wood, and 15 Ore when enacted.`,
    },
    l410: {
      id: "l410",
      img: "l410.webp",
      cost: [6],
      max: 1,
      incomeType: "none",
      limit: 50,
      title: "Magic Absorption",
      description: () =>
        `The enemy loses 1 level(s) on all Magic School spells.`,
    },
    l420: {
      id: "l420",
      img: "l420.webp",
      cost: [5],
      max: 1,
      incomeType: "none",
      limit: 50,
      title: "Animate Dead V",
      description: () => `Your heroes gain +500 maximum Necromantic Energy.`,
    },
    l401: {
      id: "l401",
      img: "l401.webp",
      cost: [4],
      max: 1,
      incomeType: "none",
      limit: 50,
      title: "Morituri te Salutant",
      description: () =>
        `Friendly creatures can make +1 counterattacks per round.`,
    },
    l411: {
      id: "l411",
      img: "l411.webp",
      cost: [4, 4],
      max: 2,
      incomeType: "none",
      limit: 50,
      title: "Death's Presence",
      description: ({ lvl }: LVL) =>
        `Enemy non-Necropolis creatures deal –${Math.min(10, lvl * 5)}% and take +${Math.min(10, lvl * 5)}% Damage. Your non-Necropolis creatures gain the opposite effect.`,
    },
  },
  temple: {
    l000: {
      id: "l000",
      img: "l000.webp",
      cost: [1],
      max: 1,
      incomeType: "once",
      income: {
        gold: 2500,
        wood: 5,
        ore: 5,
      },
      limit: 0,
      title: "Resource Riches I",
      description: () =>
        `Provides a one-time allotment of 2500 Gold, 5 Wood, and 5 Ore when enacted.`,
    },
    l010: {
      id: "l010",
      img: "l010.webp",
      cost: [4],
      max: 1,
      incomeType: "none",
      limit: 0,
      title: "Training: Scouting",
      description: ({ lvl }: LVL) =>
        `Your heroes gain ${Math.min(2, lvl)} Sight radius.`,
    },
    l020: {
      id: "l020",
      img: "l020.webp",
      cost: [2],
      max: 1,
      incomeType: "daily",
      income: {
        astrology: 250,
      },
      limit: 0,
      title: "Faith in Magic",
      description: () => `Produces 250 Astrology points daily.`,
    },
    l001: {
      id: "l001",
      img: "l001.webp",
      cost: [3, 2],
      max: 2,
      incomeType: "none",
      limit: 0,
      title: "Elite Swordsmen",
      description: ({ lvl }: LVL) =>
        `Swordsman growth in your cities increases by 4. They gain ${Math.min(4, lvl * 2)} Defense.`,
    },
    l011: {
      id: "l011",
      img: "l011.webp",
      cost: [3, 2],
      max: 2,
      incomeType: "none",
      limit: 0,
      title: "Elite Crossbowman",
      description: ({ lvl }: LVL) =>
        `Crossbowman growth in your cities increases by 4. They gain ${Math.min(4, lvl * 2)} Attack.`,
    },
    l021: {
      id: "l021",
      img: "l021.webp",
      cost: [1],
      max: 1,
      incomeType: "none",
      limit: 0,
      title: "Inquisition Crusade",
      description: () =>
        `Friendly creatures deal +25% Damage to summoned enemy creatures.`,
    },
    l100: {
      id: "l100",
      img: "l100.webp",
      cost: [3, 3],
      max: 2,
      incomeType: "daily",
      income: {
        gold: 500,
      },
      limit: 5,
      title: "Tax Collectors",
      description: ({ lvl }: LVL) =>
        `Produces ${Math.min(1000, lvl * 500)} Gold daily.`,
    },
    l110: {
      id: "l110",
      img: "l110.webp",
      cost: [2, 2],
      max: 2,
      incomeType: "daily",
      income: {
        gems: 1,
      },
      limit: 5,
      title: "Mining: Gems",
      description: ({ lvl }: LVL) =>
        `Produces ${Math.min(2, lvl)} Gem(s) daily.`,
    },
    l120: {
      id: "l120",
      img: "l120.webp",
      cost: [2, 2],
      max: 2,
      incomeType: "none",
      limit: 5,
      title: "Heroes of Tales",
      description: ({ lvl }: LVL) =>
        `Your heroes gain ${Math.min(2, lvl)} Morale.`,
    },
    l101: {
      id: "l101",
      img: "l101.webp",
      cost: [3, 2],
      max: 2,
      incomeType: "none",
      limit: 5,
      title: "Elite Griffins",
      description: ({ lvl }: LVL) =>
        `Griffin growth in your cities increases by 2. They gain ${Math.min(10, lvl * 5)} HP.`,
    },
    l111: {
      id: "l111",
      img: "l111.webp",
      cost: [3, 2],
      max: 2,
      incomeType: "none",
      limit: 5,
      title: "Elite Lightweavers",
      description: ({ lvl }: LVL) =>
        `Lightweaver growth in your cities increases by 2. They deal +${Math.min(4, lvl * 2)} Damage.`,
    },
    l121: {
      id: "l121",
      img: "l121.webp",
      cost: [3, 3],
      max: 2,
      incomeType: "none",
      limit: 5,
      title: "Execute Excellence",
      description: ({ lvl }: LVL) =>
        `All positive effects on friendly creatures last ${Math.min(2, lvl)} additional round(s).`,
    },
    l131: {
      id: "l131",
      img: "l131.webp",
      cost: [6],
      max: 1,
      incomeType: "none",
      limit: 5,
      title: "Swift Reflexes",
      description: () => `Friendly creatures gain 1 Initiative.`,
    },
    l200: {
      id: "l200",
      img: "l200.webp",
      cost: [2],
      max: 1,
      incomeType: "once",
      income: {
        gold: 5000,
        wood: 10,
        ore: 10,
      },
      limit: 15,
      title: "Resource Riches II",
      description: () =>
        `Provides a one-time allotment of 5000 Gold, 10 Wood, and 10 Ore when enacted.`,
    },
    l210: {
      id: "l210",
      img: "l210.webp",
      cost: [4, 4],
      max: 2,
      incomeType: "none",
      limit: 15,
      title: "Coinage Reform",
      description: ({ lvl }: LVL) =>
        `Your sources of Gold produce +${Math.min(20, lvl * 10)}% Gold.`,
    },
    l220: {
      id: "l220",
      img: "l220.webp",
      cost: [3],
      max: 1,
      incomeType: "none",
      limit: 15,
      title: "Sun's Grace",
      description: () => `Daylight spells of your heroes gain 1 level(s).`,
    },
    l230: {
      id: "l230",
      img: "l230.webp",
      cost: [6],
      max: 1,
      incomeType: "none",
      limit: 15,
      title: "Architect's Mastery",
      description: () => `You can construct +1 building(s) daily.`,
    },
    l201: {
      id: "l201",
      img: "l201.webp",
      cost: [3, 2],
      max: 2,
      incomeType: "none",
      limit: 15,
      title: "Elite Cavalry",
      description: ({ lvl }: LVL) =>
        `Cavalry growth in your cities increases by 1. Their attacks ignore ${Math.min(10, lvl * 5)}% of the target’s Defense and they gain 1 Speed.`,
    },
    l211: {
      id: "l211",
      img: "l211.webp",
      cost: [3, 3],
      max: 2,
      incomeType: "none",
      limit: 15,
      title: "Training: Melee Combat",
      description: ({ lvl }: LVL) =>
        `Friendly creatures deal +${Math.min(10, lvl * 5)}% and take –${Math.min(10, lvl * 5)}% Melee Damage. This effect is doubled for non-Temple friendly creatures.`,
    },
    l221: {
      id: "l221",
      img: "l221.webp",
      cost: [3, 3],
      max: 2,
      incomeType: "none",
      limit: 15,
      title: "Training: Range Combat",
      description: ({ lvl }: LVL) =>
        `Friendly creatures deal +${Math.min(10, lvl * 5)}% and take –${Math.min(10, lvl * 5)}% Long Reach and Ranged Damage. This effect is doubled for non-Temple friendly creatures.`,
    },
    l300: {
      id: "l300",
      img: "l300.webp",
      cost: [3, 3],
      max: 2,
      incomeType: "none",
      limit: 30,
      title: "Training: Attack",
      description: ({ lvl }: LVL) =>
        `Your heroes gain ${Math.min(4, lvl * 2)} Attack.`,
    },
    l310: {
      id: "l310",
      img: "l310.webp",
      cost: [3, 3],
      max: 2,
      incomeType: "none",
      limit: 30,
      title: "Training: Defense",
      description: ({ lvl }: LVL) =>
        `Your heroes gain ${Math.min(4, lvl * 2)} Defense.`,
    },
    l320: {
      id: "l320",
      img: "l320.webp",
      cost: [3, 3],
      max: 2,
      incomeType: "none",
      limit: 30,
      title: "Training: Spell Power",
      description: ({ lvl }: LVL) =>
        `Your heroes gain ${Math.min(4, lvl * 2)} Spell Power.`,
    },
    l330: {
      id: "l330",
      img: "l330.webp",
      cost: [3, 3],
      max: 2,
      incomeType: "none",
      limit: 30,
      title: "Training: Knowledge",
      description: ({ lvl }: LVL) =>
        `Your heroes gain ${Math.min(4, lvl * 2)} Knowledge.`,
    },
    l301: {
      id: "l301",
      img: "l301.webp",
      cost: [3, 2],
      max: 2,
      incomeType: "none",
      limit: 30,
      title: "Elite Inquisitors",
      description: ({ lvl }: LVL) =>
        `Inquisitor growth in your cities increases by 1. They ignore ${Math.min(10, lvl * 5)}% of the enemy’s Attack and they gain 1 Speed.`,
    },
    l311: {
      id: "l311",
      img: "l311.webp",
      cost: [1, 1, 1],
      max: 3,
      incomeType: "none",
      limit: 30,
      title: "Encouragement",
      description: ({ lvl }: LVL) =>
        `The chance of Morale triggering for friendly creatures increases by ${Math.min(3, lvl)}% for each point of their Morale.`,
    },
    l321: {
      id: "l321",
      img: "l321.webp",
      cost: [3, 3],
      max: 2,
      incomeType: "none",
      limit: 30,
      title: " Vengeful Strike",
      description: () =>
        `Friendly creatures’ counterattacks deal +50%/100% Damage.`,
    },
    l400: {
      id: "l400",
      img: "l400.webp",
      cost: [3],
      max: 1,
      incomeType: "once",
      income: {
        gold: 7500,
        wood: 15,
        ore: 15,
      },
      limit: 50,
      title: "Resource Riches III",
      description: () =>
        `Provides a one-time allotment of 7500 Gold, 15 Wood, and 15 Ore when enacted.`,
    },
    l410: {
      id: "l410",
      img: "l410.webp",
      cost: [4],
      max: 1,
      incomeType: "none",
      limit: 50,
      title: "Power of Faith",
      description: () =>
        `All your Temple heroes can learn any spells of any tier.`,
    },
    l401: {
      id: "l401",
      img: "l401.webp",
      cost: [3, 2],
      max: 2,
      incomeType: "none",
      limit: 50,
      title: "Elite Angels",
      description: ({ lvl }: LVL) =>
        `Angel growth in your cities increases by 1. They gain ${Math.min(50, lvl * 25)}% of their hero’s Attack and Defense as Attack and Defense.`,
    },
    l411: {
      id: "l411",
      img: "l411.webp",
      cost: [6],
      max: 1,
      incomeType: "none",
      limit: 50,
      title: "Hero's Blessing",
      description: () =>
        `Friendly creatures gain 25% of their hero’s Spell Power and Knowledge as Attack and Defense respectively.`,
    },
    l421: {
      id: "l421",
      img: "l421.webp",
      cost: [4],
      max: 1,
      incomeType: "none",
      limit: 50,
      title: "Sacred Lands",
      description: () =>
        `Friendly creatures are immune to negative effects when fighting on their Native Terrain.`,
    },
  },
} as const;
// { lvl }: LVL
// ${Math.min(20, lvl * 10)}
// On-screen layout for each faction's law board: each inner array is a group
// (column) of law ids, mirroring the original nested-array positions.
export const LAW_LAYOUT: {
  // Each faction's layout references only that faction's own law ids.
  [F in FactionID]: {
    left: (keyof (typeof LAWS)[F])[][];
    right: (keyof (typeof LAWS)[F])[][];
  };
} = {
  hive: {
    left: [
      ["l000", "l010", "l020", "l030"],
      ["l100", "l110", "l120"],
      ["l200", "l210", "l220"],
      ["l300", "l310"],
      ["l400", "l410", "l420"],
    ],
    right: [
      ["l001", "l011", "l021"],
      ["l101", "l111", "l121"],
      ["l201", "l211", "l221", "l231"],
      ["l301", "l311"],
      ["l401", "l411", "l421"],
    ],
  },
  schism: {
    left: [
      ["l000", "l010", "l020"],
      ["l100", "l110", "l120", "l130"],
      ["l200", "l210", "l220", "l230"],
      ["l300", "l310", "l320", "l330"],
      ["l400", "l410", "l430"],
    ],
    right: [
      ["l001", "l011", "l021"],
      ["l101", "l111", "l121", "l131"],
      ["l201", "l211", "l221"],
      ["l301", "l311", "l321", "l331"],
      ["l401", "l411", "l421"],
    ],
  },
  dungeon: {
    left: [
      ["l000", "l010", "l020"],
      ["l100", "l110", "l120"],
      ["l200", "l210", "l220", "l230"],
      ["l300", "l310", "l320", "l330"],
      ["l400", "l410", "l420"],
    ],
    right: [
      ["l001", "l011", "l021"],
      ["l101", "l111", "l121", "l131"],
      ["l201", "l211", "l221", "l231"],
      ["l301", "l311", "l321"],
      ["l401", "l411"],
    ],
  },
  grove: {
    left: [
      ["l000", "l010", "l020"],
      ["l100", "l110", "l120"],
      ["l200", "l210", "l220", "l230"],
      ["l300", "l310", "l320", "l330"],
      ["l400", "l410", "l420", "l430"],
    ],
    right: [
      ["l001", "l011"],
      ["l101", "l111", "l121"],
      ["l201", "l211"],
      ["l301", "l311", "l321"],
      ["l401", "l411", "l421"],
    ],
  },
  necropolis: {
    left: [
      ["l000", "l010", "l020", "l030"],
      ["l100", "l110", "l120", "l130"],
      ["l200", "l210", "l220", "l230"],
      ["l300", "l310", "l320"],
      ["l400", "l410", "l420"],
    ],
    right: [
      ["l001", "l011", "l021"],
      ["l101", "l111", "l121"],
      ["l201", "l211", "l221"],
      ["l301", "l311", "l321"],
      ["l401", "l411"],
    ],
  },
  temple: {
    left: [
      ["l000", "l010", "l020"],
      ["l100", "l110", "l120"],
      ["l200", "l210", "l220", "l230"],
      ["l300", "l310", "l320", "l330"],
      ["l400", "l410"],
    ],
    right: [
      ["l001", "l011", "l021"],
      ["l101", "l111", "l121", "l131"],
      ["l201", "l211", "l221"],
      ["l301", "l311", "l321"],
      ["l401", "l411", "l421"],
    ],
  },
};

type LVL = { lvl: number };
type Sight = { sight: number };

export type FactionID = keyof typeof LAWS;

// One faction's full law map.
export type FactionLaws = (typeof LAWS)[FactionID];

// Every law id across all factions. `keyof FactionLaws` can't be used here:
// `keyof` over a union yields only the keys shared by every member (the
// intersection), which drops faction-unique ids — so build the union explicitly.
export type LawID = { [F in FactionID]: keyof (typeof LAWS)[F] }[FactionID];

// Every law's config across all factions.
export type LawType = {
  [F in FactionID]: (typeof LAWS)[F][keyof (typeof LAWS)[F]];
}[FactionID];
